CREATE TABLE SCHEDULE_AI_CHAT_LOG (
  CHAT_ID      NUMBER PRIMARY KEY,
  SCHEDULE_ID  NUMBER NOT NULL,
  SESSION_ID   VARCHAR2(64),
  USER_NO      NUMBER,
  QUESTION     CLOB NOT NULL,
  ANSWER       CLOB NOT NULL,
  CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE SEQUENCE SEQ_SCHEDULE_AI_CHAT_LOG START WITH 1 INCREMENT BY 1;

ALTER TABLE SCHEDULE_AI_CHAT_LOG
  ADD CONSTRAINT FK_SCHAT_SCHEDULE
  FOREIGN KEY (SCHEDULE_ID) REFERENCES SCHEDULE(SCHEDULE_ID);

CREATE INDEX IDX_SCHAT_SCHEDULE ON SCHEDULE_AI_CHAT_LOG(SCHEDULE_ID);
