CREATE TABLE SCHEDULE_AI_CACHE (
  AI_ID           NUMBER PRIMARY KEY,
  SCHEDULE_ID     NUMBER NOT NULL,
  KIND            VARCHAR2(30) NOT NULL,  -- SUMMARY | HASHTAGS | DAY_HIGHLIGHTS
  CONTENT         CLOB NOT NULL,          -- JSON 문자열 저장
  MODEL           VARCHAR2(50),
  PROMPT_VERSION  VARCHAR2(20),
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE SEQUENCE SEQ_SCHEDULE_AI_CACHE START WITH 1 INCREMENT BY 1;

ALTER TABLE SCHEDULE_AI_CACHE
  ADD CONSTRAINT FK_SAI_SCHEDULE
  FOREIGN KEY (SCHEDULE_ID) REFERENCES SCHEDULE(SCHEDULE_ID);

ALTER TABLE SCHEDULE_AI_CACHE
  ADD CONSTRAINT UK_SAI_UNQ UNIQUE (SCHEDULE_ID, KIND);

CREATE INDEX IDX_SAI_SCHEDULE ON SCHEDULE_AI_CACHE(SCHEDULE_ID);
