ALTER TABLE user_tb
MODIFY PROFILE_IMAGE VARCHAR2(700);


commit;

DELETE FROM bike_rental_station;
DELETE FROM bike_repair_shop;

UPDATE bike_rental_station
SET bike_count = ROUND(DBMS_RANDOM.VALUE(40, 60));

ALTER TABLE bike_rental_station
ADD phone VARCHAR2(20);

ALTER TABLE bike_rental_station
ADD phone VARCHAR2(20);

UPDATE bike_rental_station
SET phone = '010-' || LPAD(TRUNC(DBMS_RANDOM.VALUE(1000, 9999)), 4, '0') 
                || '-' || LPAD(TRUNC(DBMS_RANDOM.VALUE(1000, 9999)), 4, '0');

commit;

CREATE TABLE bike_rental_station (
    rental_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR2(100) NOT NULL,
    address VARCHAR2(255),

    lat NUMBER(10,7) NOT NULL,
    lng NUMBER(10,7) NOT NULL,

    open_time VARCHAR2(50),
    bike_count NUMBER,

    source VARCHAR2(50) NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO bike_rental_station
(name, address, lat, lng, open_time, bike_count, source)
VALUES
('서울역 자전거 대여소',
 '서울 중구 서울역',
 37.5563000,
 126.9723000,
 '09:00~22:00',
 20,
 'SEOUL_OPEN_API');
