DROP TABLE SURVEY_ANSWER CASCADE CONSTRAINTS;
DROP TABLE SURVEY_RESPONSE CASCADE CONSTRAINTS;
DROP TABLE SURVEY_OPTION CASCADE CONSTRAINTS;
DROP TABLE SURVEY_QUESTION CASCADE CONSTRAINTS;
DROP TABLE SURVEY CASCADE CONSTRAINTS;

DROP SEQUENCE SURVEY_SEQ;
DROP SEQUENCE SURVEY_Q_SEQ;
DROP SEQUENCE SURVEY_OPT_SEQ;
DROP SEQUENCE SURVEY_RESP_SEQ;
DROP SEQUENCE SURVEY_ANS_SEQ;

CREATE TABLE SURVEY (
    SURVEY_ID        NUMBER PRIMARY KEY,
    TITLE            VARCHAR2(200) NOT NULL,
    DESCRIPTION      VARCHAR2(500),
    SURVEY_TYPE      VARCHAR2(20),   -- SURVEY / RESEARCH
    EST_TIME_MIN     NUMBER,
    REWARD_POINT     NUMBER,
    ACTIVE_YN        CHAR(1) DEFAULT 'Y',
    CREATED_AT       DATE DEFAULT SYSDATE
);

COMMENT ON TABLE SURVEY IS '설문조사 및 심층 리서치 마스터';
COMMENT ON COLUMN SURVEY.SURVEY_TYPE IS 'SURVEY: 일반 설문 / RESEARCH: 심층 리서치';

CREATE SEQUENCE SURVEY_SEQ;

CREATE TABLE SURVEY_QUESTION (
    QUESTION_ID     NUMBER PRIMARY KEY,
    SURVEY_ID       NUMBER NOT NULL,
    QUESTION_NO     NUMBER NOT NULL,
    QUESTION_TEXT   VARCHAR2(500) NOT NULL,
    QUESTION_TYPE   VARCHAR2(30), -- SINGLE, MULTI, TEXT, SCORE
    REQUIRED_YN     CHAR(1) DEFAULT 'Y',
    CREATED_AT      DATE DEFAULT SYSDATE,
    CONSTRAINT FK_SURVEY_Q FOREIGN KEY (SURVEY_ID)
        REFERENCES SURVEY(SURVEY_ID)
);

COMMENT ON TABLE SURVEY_QUESTION IS '설문 문항';

CREATE SEQUENCE SURVEY_Q_SEQ;


CREATE TABLE SURVEY_OPTION (
    OPTION_ID       NUMBER PRIMARY KEY,
    QUESTION_ID     NUMBER NOT NULL,
    OPTION_NO       NUMBER,
    OPTION_TEXT     VARCHAR2(200),
    CREATED_AT      DATE DEFAULT SYSDATE,
    CONSTRAINT FK_SURVEY_OPT FOREIGN KEY (QUESTION_ID)
        REFERENCES SURVEY_QUESTION(QUESTION_ID)
);

COMMENT ON TABLE SURVEY_OPTION IS '설문 문항 선택지';

CREATE SEQUENCE SURVEY_OPT_SEQ;


CREATE TABLE SURVEY_RESPONSE (
    RESPONSE_ID     NUMBER PRIMARY KEY,
    SURVEY_ID       NUMBER NOT NULL,
    USER_NO         NUMBER NOT NULL,
    COMPLETED_YN    CHAR(1) DEFAULT 'N',
    COMPLETED_AT    DATE,
    CREATED_AT      DATE DEFAULT SYSDATE,
    CONSTRAINT FK_SURVEY_RESP FOREIGN KEY (SURVEY_ID)
        REFERENCES SURVEY(SURVEY_ID)
);

COMMENT ON TABLE SURVEY_RESPONSE IS '설문 응답 헤더';

CREATE SEQUENCE SURVEY_RESP_SEQ;


CREATE TABLE SURVEY_ANSWER (
    ANSWER_ID       NUMBER PRIMARY KEY,
    RESPONSE_ID     NUMBER NOT NULL,
    QUESTION_ID     NUMBER NOT NULL,
    OPTION_ID       NUMBER,
    ANSWER_TEXT     VARCHAR2(1000),
    SCORE_VALUE     NUMBER,
    CREATED_AT      DATE DEFAULT SYSDATE,
    CONSTRAINT FK_SURVEY_ANS_RESP FOREIGN KEY (RESPONSE_ID)
        REFERENCES SURVEY_RESPONSE(RESPONSE_ID),
    CONSTRAINT FK_SURVEY_ANS_Q FOREIGN KEY (QUESTION_ID)
        REFERENCES SURVEY_QUESTION(QUESTION_ID)
);

COMMENT ON TABLE SURVEY_ANSWER IS '설문 실제 응답';

CREATE SEQUENCE SURVEY_ANS_SEQ;


INSERT INTO SURVEY VALUES (
    SURVEY_SEQ.NEXTVAL,
    '자전거 여행 일정 추천, 얼마나 만족하셨나요?',
    '소중한 의견 감사합니다. 더 나은 자전거 여행 서비스를 만들겠습니다 🚴',
    'SURVEY',
    3,
    30,
    'Y',
    SYSDATE
);


INSERT INTO SURVEY_QUESTION VALUES (
    SURVEY_Q_SEQ.NEXTVAL,
    1,
    1,
    '최근 이용한 기능은 무엇인가요?',
    'MULTI',
    'Y',
    SYSDATE
);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 1, 1, 'AI 일정 추천', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 1, 2, '여행 설정(취향 선택)', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 1, 3, '지도/코스 확인', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 1, 4, '체크리스트', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 1, 5, '아직 사용 전', SYSDATE);

INSERT INTO SURVEY_QUESTION VALUES (
    SURVEY_Q_SEQ.NEXTVAL,
    1,
    2,
    'AI 일정 추천은 얼마나 도움이 되었나요?',
    'SINGLE',
    'Y',
    SYSDATE
);
-- ⭐⭐⭐⭐⭐
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 2, 1, '매우 만족', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 2, 2, '만족', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 2, 3, '보통', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 2, 4, '아쉬움', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 2, 5, '전혀 도움 안 됨', SYSDATE);

INSERT INTO SURVEY_QUESTION VALUES (
    SURVEY_Q_SEQ.NEXTVAL,
    1,
    3,
    '추천된 일정의 난이도는 어땠나요?',
    'SINGLE',
    'Y',
    SYSDATE
);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 3, 1, '너무 쉬웠다', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 3, 2, '적당했다', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 3, 3, '조금 어려웠다', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 3, 4, '많이 어려웠다', SYSDATE);

INSERT INTO SURVEY_QUESTION VALUES (
    SURVEY_Q_SEQ.NEXTVAL,
    1,
    4,
    '일정에서 가장 마음에 들었던 요소는 무엇인가요?',
    'SINGLE',
    'Y',
    SYSDATE
);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 4, 1, '코스 구성', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 4, 2, '풍경 / 감성', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 4, 3, '휴식 포인트', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 4, 4, '거리 / 난이도', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 4, 5, '전체 흐름', SYSDATE);

INSERT INTO SURVEY_QUESTION VALUES (
    SURVEY_Q_SEQ.NEXTVAL,
    1,
    5,
    '일정 사용 중 불편했던 점이 있었다면 무엇인가요?',
    'MULTI',
    'N',
    SYSDATE
);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 5, 1, '설정 과정이 헷갈렸다', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 5, 2, '일정이 내 취향과 달랐다', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 5, 3, '수정이 어려웠다', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 5, 4, '정보가 부족했다', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 5, 5, '불편함 없음', SYSDATE);

INSERT INTO SURVEY_QUESTION VALUES (
    SURVEY_Q_SEQ.NEXTVAL,
    1,
    6,
    '다음에 추가되면 좋을 기능은 무엇인가요?',
    'MULTI',
    'N',
    SYSDATE
);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 6, 1, '실시간 날씨 반영', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 6, 2, '체력 / 난이도 자동 조절', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 6, 3, '친구와 일정 공유', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 6, 4, '여행 후 자동 요약', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 6, 5, '지금도 충분하다', SYSDATE);

INSERT INTO SURVEY_QUESTION VALUES (
    SURVEY_Q_SEQ.NEXTVAL,
    1,
    7,
    '이 서비스를 지인에게 추천하고 싶으신가요?',
    'SCORE',
    'Y',
    SYSDATE
);


SELECT SURVEY_ID, TITLE, SURVEY_TYPE, REWARD_POINT
FROM SURVEY
WHERE ACTIVE_YN = 'Y'
ORDER BY CREATED_AT DESC;

-- 심층리서치
INSERT INTO SURVEY VALUES (
    SURVEY_SEQ.NEXTVAL,
    'AI 자전거 여행 일정, 어떻게 느끼셨나요? (인터뷰형)',
    '여러분의 경험 하나하나가 AI 추천을 더 똑똑하게 만듭니다. 감사합니다 🙏',
    'RESEARCH',
    20,
    50,
    'Y',
    SYSDATE
);
INSERT INTO SURVEY_QUESTION VALUES (
    SURVEY_Q_SEQ.NEXTVAL,
    2,
    1,
    '일정 생성 전 여행 설정(취향 선택) 과정은 어땠나요?',
    'SINGLE',
    'Y',
    SYSDATE
);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 7, 1, '매우 쉬웠다', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 7, 2, '어렵지 않았다', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 7, 3, '조금 헷갈렸다', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 7, 4, '많이 헷갈렸다', SYSDATE);
INSERT INTO SURVEY_QUESTION VALUES (
    SURVEY_Q_SEQ.NEXTVAL,
    2,
    2,
    '왜 그렇게 느끼셨나요?',
    'TEXT',
    'N',
    SYSDATE
);

INSERT INTO SURVEY_QUESTION VALUES (
    SURVEY_Q_SEQ.NEXTVAL,
    2,
    3,
    'AI가 추천한 일정은 실제 기대와 얼마나 비슷했나요?',
    'SINGLE',
    'Y',
    SYSDATE
);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 9, 1, '거의 완전히 일치', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 9, 2, '대체로 비슷', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 9, 3, '반반 정도', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 9, 4, '많이 달랐다', SYSDATE);
INSERT INTO SURVEY_QUESTION VALUES (
    SURVEY_Q_SEQ.NEXTVAL,
    2,
    4,
    '가장 달랐던 부분은 무엇이었나요?',
    'MULTI',
    'N',
    SYSDATE
);

INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 10, 1, '거리', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 10, 2, '난이도', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 10, 3, '분위기', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 10, 4, '휴식', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 10, 5, '기타', SYSDATE);


INSERT INTO SURVEY_QUESTION VALUES (
    SURVEY_Q_SEQ.NEXTVAL,
    2,
    5,
    '추천 일정을 그대로 사용했나요?',
    'SINGLE',
    'Y',
    SYSDATE
);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 11, 1, '그대로 사용했다', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 11, 2, '일부 수정해서 사용했다', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 11, 3, '거의 사용하지 않았다', SYSDATE);
INSERT INTO SURVEY_QUESTION VALUES (
    SURVEY_Q_SEQ.NEXTVAL,
    2,
    6,
    '수정했다면 어떤 점을 왜 수정했나요?',
    'TEXT',
    'N',
    SYSDATE
);
INSERT INTO SURVEY_QUESTION VALUES (
    SURVEY_Q_SEQ.NEXTVAL,
    2,
    7,
    'AI가 추천할 때 추가로 알았으면 하는 정보가 있다면 무엇인가요?',
    'MULTI',
    'N',
    SYSDATE
);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 13, 1, '당일 컨디션', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 13, 2, '체력 수준', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 13, 3, '날씨', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 13, 4, '이전 여행 기록', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 13, 5, '동행자의 성향', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 13, 6, '기타', SYSDATE);
INSERT INTO SURVEY_QUESTION VALUES (
    SURVEY_Q_SEQ.NEXTVAL,
    2,
    8,
    '일정 결과를 보며 가장 신뢰가 갔던 이유는 무엇인가요?',
    'SINGLE',
    'Y',
    SYSDATE
);

INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 14, 1, '내 취향이 잘 반영됨', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 14, 2, '코스 설명이 이해 쉬움', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 14, 3, '이전 경험과 비슷함', SYSDATE);
INSERT INTO SURVEY_OPTION VALUES (SURVEY_OPT_SEQ.NEXTVAL, 14, 4, '전체 흐름이 자연스러움', SYSDATE);


INSERT INTO SURVEY_QUESTION VALUES (
    SURVEY_Q_SEQ.NEXTVAL,
    2,
    9,
    'AI 추천 일정에서 신뢰가 떨어졌던 순간이 있었다면 적어주세요.',
    'TEXT',
    'N',
    SYSDATE
);
INSERT INTO SURVEY_QUESTION VALUES (
    SURVEY_Q_SEQ.NEXTVAL,
    2,
    10,
    '이 서비스가 더 좋아지기 위해 꼭 개선되었으면 하는 점은 무엇인가요?',
    'TEXT',
    'Y',
    SYSDATE
);

SELECT QUESTION_NO, QUESTION_TEXT, QUESTION_TYPE
FROM SURVEY_QUESTION
WHERE SURVEY_ID = 1
ORDER BY QUESTION_NO;
