DROP TABLE PLACE_TAGS CASCADE CONSTRAINTS;

CREATE TABLE PLACE_TAGS (
    TAG_ID       NUMBER(10)     NOT NULL,
    PLACE_ID     NUMBER(10)     NOT NULL,
    ITEM_ID      NUMBER(10)     NOT NULL,
    CREATED_AT   DATE,
    PRIMARY KEY (TAG_ID),
    FOREIGN KEY (PLACE_ID) REFERENCES PLACES(PLACE_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES CHECKLIST(ITEM_ID)
);

COMMENT ON TABLE PLACE_TAGS IS '여행지별 체크리스트 태그 매핑';
COMMENT ON COLUMN PLACE_TAGS.TAG_ID IS '고유 ID';
COMMENT ON COLUMN PLACE_TAGS.PLACE_ID IS '여행지 ID';
COMMENT ON COLUMN PLACE_TAGS.ITEM_ID IS '체크리스트 항목 ID';
COMMENT ON COLUMN PLACE_TAGS.CREATED_AT IS '등록일';


DROP SEQUENCE PLACE_TAGS_SEQ;

-- 시퀀스 생성
CREATE SEQUENCE PLACE_TAGS_SEQ
  START WITH 1                -- 시작 번호
  INCREMENT BY 1              -- 증가값
  MAXVALUE 9999999999         -- 최대값
  CACHE 2                     -- 메모리 캐시
  NOCYCLE;                     -- 1부터 다시 시작하지 않음
